name: Lovely Valentine CD

# Build push CICD for multiplatform images
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build Push Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Loign to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          content: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ secrets.USERNAME }}/toode:latest
